#include "SFrameRenderInspectorUI.h"
#include "FrameRenderInspectorUIPrivate.h"

#include "Common/SFrameRenderInspectorUIConstruct.inl"
#include "Texture/SFrameRenderInspectorTextureSection.inl"
#include "Texture/SFrameRenderInspectorTextureState.inl"
#include "Texture/SFrameRenderInspectorTextureInteractions.inl"
#include "Texture/SFrameRenderInspectorTextureHelpers.inl"
#include "Buffer/SFrameRenderInspectorBufferSection.inl"
#include "Buffer/SFrameRenderInspectorBufferState.inl"
#include "Buffer/SFrameRenderInspectorBufferInteractions.inl"
#include "Buffer/SFrameRenderInspectorBufferHelpers.inl"
#include "Options/SFrameRenderInspectorOptionsSection.inl"
#include "Options/SFrameRenderInspectorOptionsState.inl"
#include "Options/SFrameRenderInspectorOptionsInteractions.inl"
#include "Options/SFrameRenderInspectorOptionsHelpers.inl"
